server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: notification
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
    listener:
      simple:
        observation-enabled: true

rabbitmq:
  exchange: ${RABBITMQ_EXCHANGE:bio.library.exchange}
  queue: ${RABBITMQ_QUEUE:bio.library.notification.queue}
  routing-key: ${RABBITMQ_ROUTING_KEY:loan.event}

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces
